#:set color_cosmos 0.2, 0, 0.1, 1

<MainScreen>:
    MDBoxLayout: 
        orientation: 'vertical'     
        padding: '50dp' 
        spacing: '30dp'
        MDIconButton:
            icon: "cog" # cog - шестерня
            pos_hint: {"right": 1, "top": 1}
            icon_size: '50dp'
        MDLabel:
            text: "SHOOTER"
            halign: 'center'
            font_size: '60sp'
        Image:
            source: 'assets/images/rocket.png'
            size_hint_y: 0.7
            size: dp(50), dp(50)
            allow_stretch: True
        MDRectangleFlatButton: # Більш сучасний - MDButton
            text: "PLAY"
            font_size: '60sp'
            pos_hint: {'center_x': 0.5,'center_y': 0.5}
            theme_text_color: "Custom"
            text_color: "white"
            line_color: "red"
            on_press:
                root.manager.current = 'game'

# --- Створюється новий клас Ship як успадкований від Image ---
<Ship@Image>:
    source: 'assets/images/rocket.png'
    size_hint: None, None
    size: dp(100), dp(300)
    # size: dp(50), dp(50)

<GameScreen>:
    MDFloatLayout:
        md_bg_color: color_cosmos
        MDFloatLayout:
            id: game
            MDFloatLayout:
                id: back
            MDFloatLayout:
                id: front
                Ship:  
                    id: ship
                    center: root.center       

        MDFloatLayout:
            id: interface
        
            MDBoxLayout:
                spacing: dp(20)
                padding: dp(20)
                MDFloatingActionButton:
                    icon: "arrow-left-bold"
                    on_press: root.pressKey('left')
                    on_release: root.releaseKey('left')
                MDFloatingActionButton:
                    icon: "arrow-right-bold"
                    on_press: root.pressKey('right')
                    on_release: root.releaseKey('right')
                Widget:
                MDFloatingActionButton:
                    icon: "arrow-up-bold"
                    on_press: root.pressKey('shot')
                    on_release: root.releaseKey('shot')
                
<Shot>:
    size_hint: None, None
    size: 20, 20
    md_bg_color: app.theme_cls.primary_color
                
                
                
                
                
                
