#:set color_cosmos 0.2, 0, 0.1, 1


<MainScreen>:
    MDBoxLayout: 
        orientation: 'vertical'     
        padding: '50dp' 
        spacing: '30dp'
        
        MDIconButton:
            icon: "cog"
            pos_hint: {"right": 1, "top": 1}
            icon_size: '50dp'
            
        Image:
            source: 'assets/images/rocket.png'
            size_hint_y: 0.7
            size: dp(50), dp(50)
            allow_stretch: True
            
        MDRectangleFlatButton:
            text: "PLAY"
            font_size: '60sp'
            pos_hint: {'center_x': 0.5,'center_y': 0.5}
            on_press:
                root.manager.current = 'game'

<Ship>:
    size_hint: None, None
    # canvas.before:
    #     Color: 
    #         rgba: 1, 0, 0, 1
    #     Rectangle:
    #         size: self.size
    #         pos: self.pos

<PlayerShip@Ship>:
    source: 'assets/images/rocket.png'
    size: dp(100), dp(243)


<EnemyShip@Ship>:
    source: 'assets/images/ufo.png'

<GameScreen>:
    MDFloatLayout:
        md_bg_color: color_cosmos
        
        MDFloatLayout:
            id: game
            
            MDFloatLayout:
                id: back
                
            MDFloatLayout:
                id: front
                PlayerShip:  
                    id: ship
                    pos: root.center_x, dp(50)     

        MDFloatLayout:
            id: interface

            MDBoxLayout:
                spacing: dp(10)
                padding: dp(10)
                pos_hint: {"top": 1}
                size_hint_y: None
                height: dp(60)

                MDIcon:
                    icon: "heart"
                    font_size: '40sp'
                    size_hint: None, None
                    size: dp(40), dp(40)
                    pos_hint: {"center_y": 0.5}
                    color: 1, 0, 0, 1

                MDProgressBar:
                    id: hp_status
                    value: (ship.hp / ship.max_hp) * 100
                    size_hint_x: 1
                    size_hint_y: None
                    height: dp(10)
                    pos_hint: {"center_y": 0.5}
                    color: app.theme_cls.accent_color

                MDIcon:
                    icon: "clock-outline"
                    font_size: '35sp'
                    size_hint: None, None
                    size: dp(35), dp(35)
                    pos_hint: {"center_y": 0.5}
                    color: 1, 1, 1, 1

                MDLabel:
                    text: f"{int(root.game_time) // 60:02d}:{int(root.game_time) % 60:02d}"
                    font_size: '18sp'
                    size_hint: None, None
                    size: dp(45), dp(40)
                    halign: "center"
                    valign: "middle"

                MDFloatingActionButton:
                    icon: "pause"
                    size_hint: None, None
                    size: dp(50), dp(50)
                    pos_hint: {"center_y": 0.5}
                    on_press: root.show_menu()

                # MDWidget:

            MDBoxLayout:
                spacing: dp(20)
                padding: dp(20)
                
                MDFloatingActionButton:
                    icon: "arrow-left-bold"
                    on_press: root.pressKey('left')
                    on_release: root.releaseKey('left')

                MDFloatingActionButton:
                    icon: "arrow-right-bold"
                    md_bg_color: app.theme_cls.primary_color
                    on_press: root.pressKey('right')
                    on_release: root.releaseKey('right')
                    
                Widget:
                
                MDFloatingActionButton:
                    icon: "arrow-up-bold"
                    md_bg_color: app.theme_cls.primary_color
                    on_press: root.pressKey('shot')
                    on_release: root.releaseKey('shot')


<Shot>:
    size_hint: None, None
    size: 20, 20
    md_bg_color: app.theme_cls.accent_color


<GameOverScreen>:
    MDBoxLayout: 
        orientation: 'vertical'     
        padding: '50dp' 
        spacing: '30dp'
        
        MDLabel:
            text: "GAME OVER"
            font_size: '100sp'
            color: app.theme_cls.accent_color
            halign: 'center'
            
        MDIcon:
            icon: "skull"
            font_size: '220sp'
            size_hint: None, None
            pos_hint: {'center_x': 0.5}
            color: app.theme_cls.accent_color
            
        Widget:
            size_hint_y: 0.5
            
        MDRectangleFlatButton:
            text: "MENU"
            font_size: '60sp'
            pos_hint: {'center_x': 0.5}
            theme_text_color: "Custom"
            line_color: 1, 0, 0, 1
            text_color: 1, 0, 0, 1
            on_press:
                root.manager.current = 'main'